### ISSUE TITLE
gradlew test crash

### ISSUE THREAD

**Issue by tocumarian** [selenide-examples/hangman#3]
After I run gradlew test one of the tasks is crashing:

'D:\framework\IntelliJIDEAICPortable\Workspace\Hangman>gradlew test --stacktrace
:compileJava UP-TO-DATE
:compileScala UP-TO-DATE
:libs UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:compileTestJava UP-TO-DATE
:compileTestScala
[ant:scalac] warning: there was one feature warning; re-run with -feature for details

[ant:scalac] one warning found

D:\framework\IntelliJIDEAICPortable\Workspace\Hangman\test\ee\era\hangman\model\HangmanGameTest.java:41: error: unclosed character literal
    game.guessLetter('đŻ');
                     ^
D:\framework\IntelliJIDEAICPortable\Workspace\Hangman\test\ee\era\hangman\model\HangmanGameTest.java:41: error: illegal character: '\u02dd'
    game.guessLetter('đŻ');
                       ^
D:\framework\IntelliJIDEAICPortable\Workspace\Hangman\test\ee\era\hangman\model\HangmanGameTest.java:41: error: unclosed character literal
    game.guessLetter('đŻ');
                        ^
D:\framework\IntelliJIDEAICPortable\Workspace\Hangman\test\ee\era\hangman\model\HangmanTest.java:65: error: unclosed character literal
    game.guessLetter('đŻ');
                     ^
D:\framework\IntelliJIDEAICPortable\Workspace\Hangman\test\ee\era\hangman\model\HangmanTest.java:65: error: illegal character: '\u02dd'
    game.guessLetter('đŻ');
                       ^
D:\framework\IntelliJIDEAICPortable\Workspace\Hangman\test\ee\era\hangman\model\HangmanTest.java:65: error: unclosed character literal
    game.guessLetter('đŻ');
                        ^
D:\framework\IntelliJIDEAICPortable\Workspace\Hangman\test\ee\era\hangman\model\HangmanTest.java:66: error: unclosed character literal
    game.guessLetter('đ░');
                     ^
D:\framework\IntelliJIDEAICPortable\Workspace\Hangman\test\ee\era\hangman\model\HangmanTest.java:66: error: illegal character: '\u00b0'
    game.guessLetter('đ░');
                       ^
D:\framework\IntelliJIDEAICPortable\Workspace\Hangman\test\ee\era\hangman\model\HangmanTest.java:66: error: unclosed character literal
    game.guessLetter('đ░');
                        ^
D:\framework\IntelliJIDEAICPortable\Workspace\Hangman\test\ee\era\hangman\model\HangmanTest.java:67: error: unclosed character literal
    game.guessLetter('đ▓');
                     ^
D:\framework\IntelliJIDEAICPortable\Workspace\Hangman\test\ee\era\hangman\model\HangmanTest.java:67: error: illegal character: '\u02db'
    game.guessLetter('đ▓');
                       ^
D:\framework\IntelliJIDEAICPortable\Workspace\Hangman\test\ee\era\hangman\model\HangmanTest.java:67: error: unclosed character literal
    game.guessLetter('đ▓');
                        ^
D:\framework\IntelliJIDEAICPortable\Workspace\Hangman\test\ee\era\hangman\model\HangmanTest.java:68: error: unclosed character literal
    game.guessLetter('đŞ');
                     ^
D:\framework\IntelliJIDEAICPortable\Workspace\Hangman\test\ee\era\hangman\model\HangmanTest.java:68: error: illegal character: '\u00b8'
    game.guessLetter('đŞ');
                       ^
D:\framework\IntelliJIDEAICPortable\Workspace\Hangman\test\ee\era\hangman\model\HangmanTest.java:68: error: unclosed character literal
    game.guessLetter('đŞ');
                        ^
D:\framework\IntelliJIDEAICPortable\Workspace\Hangman\test\ee\era\hangman\model\HangmanTest.java:69: error: unclosed character literal
    game.guessLetter('đ┤');
                     ^
D:\framework\IntelliJIDEAICPortable\Workspace\Hangman\test\ee\era\hangman\model\HangmanTest.java:69: error: illegal character: '\u00b4'
    game.guessLetter('đ┤');
                       ^
D:\framework\IntelliJIDEAICPortable\Workspace\Hangman\test\ee\era\hangman\model\HangmanTest.java:69: error: unclosed character literal
    game.guessLetter('đ┤');
                        ^
D:\framework\IntelliJIDEAICPortable\Workspace\Hangman\test\ee\era\hangman\model\WordsTest.java:19: error: unmappable character for encoding Cp1250
        new Word("đ┤đżđ╝", "đ│đ▓đżđĚđ┤Đî"), new Word("đ┤đżđ╝", "Đ?đŻđŞĐéđ░đĚ"), new Word("đ┤đżđ╝", "Đçđ░đ╣đŻđŞđ║"),
                                                                 ^
D:\framework\IntelliJIDEAICPortable\Workspace\Hangman\test\ee\era\hangman\model\WordsTest.java:20: error: unmappable character for encoding Cp1250
        new Word("Đäđ╗đżĐÇđ░", "đ│đ▓đżđĚđ┤đŞđ║đ░"), new Word("Đäđ╗đżĐÇđ░", "đ║Đ?Đ?Đé"),
                                                                               ^
D:\framework\IntelliJIDEAICPortable\Workspace\Hangman\test\ee\era\hangman\model\WordsTest.java:20: error: unmappable character for encoding Cp1250
        new Word("Đäđ╗đżĐÇđ░", "đ│đ▓đżđĚđ┤đŞđ║đ░"), new Word("Đäđ╗đżĐÇđ░", "đ║Đ?Đ?Đé"),
                                                                                 ^
D:\framework\IntelliJIDEAICPortable\Workspace\Hangman\test\ee\era\hangman\model\WordsTest.java:21: error: unmappable character for encoding Cp1250
        new Word("Đäđ░Đ?đŻđ░", "đ▓đÁĐÇđ▒đ╗ĐÄđ┤")
                       ^
D:\framework\IntelliJIDEAICPortable\Workspace\Hangman\test\ee\era\hangman\model\WordsTest.java:26: error: unmappable character for encoding Cp1250
    count.put("Đ?đŻđŞĐéđ░đĚ", 0);
                ^
D:\framework\IntelliJIDEAICPortable\Workspace\Hangman\test\ee\era\hangman\model\WordsTest.java:29: error: unmappable character for encoding Cp1250
    count.put("đ║Đ?Đ?Đé", 0);
                  ^
D:\framework\IntelliJIDEAICPortable\Workspace\Hangman\test\ee\era\hangman\model\WordsTest.java:29: error: unmappable character for encoding Cp1250
    count.put("đ║Đ?Đ?Đé", 0);
                    ^
D:\framework\IntelliJIDEAICPortable\Workspace\Hangman\test\ee\era\hangman\model\WordsTest.java:38: error: unmappable character for encoding Cp1250
    assertTrue(count.get("Đ?đŻđŞĐéđ░đĚ") > 1000);
                           ^
D:\framework\IntelliJIDEAICPortable\Workspace\Hangman\test\ee\era\hangman\model\WordsTest.java:41: error: unmappable character for encoding Cp1250
    assertTrue(count.get("đ║Đ?Đ?Đé") > 1000);
                             ^
D:\framework\IntelliJIDEAICPortable\Workspace\Hangman\test\ee\era\hangman\model\WordsTest.java:41: error: unmappable character for encoding Cp1250
    assertTrue(count.get("đ║Đ?Đ?Đé") > 1000);
                               ^
18 errors
:compileTestScala FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileTestScala'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileTestScala'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
        at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:33)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:130)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
Caused by: org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler error output for details.
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:44)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:35)
        at org.gradle.api.internal.tasks.scala.DefaultScalaJavaJointCompiler.execute(DefaultScalaJavaJointCompiler.java:42)
        at org.gradle.api.internal.tasks.scala.DefaultScalaJavaJointCompiler.execute(DefaultScalaJavaJointCompiler.java:25)
        at org.gradle.api.internal.tasks.scala.NormalizingScalaCompiler.delegateAndHandleErrors(NormalizingScalaCompiler.java:103)
        at org.gradle.api.internal.tasks.scala.NormalizingScalaCompiler.execute(NormalizingScalaCompiler.java:52)
        at org.gradle.api.internal.tasks.scala.NormalizingScalaCompiler.execute(NormalizingScalaCompiler.java:38)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:34)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
        at org.gradle.api.tasks.scala.ScalaCompile.compile(ScalaCompile.java:138)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:579)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:562)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 47 more

BUILD FAILED

Total time: 8.544 secs'

**Comment by asolntsev** [comment]
well.. Windows again...:)

It's because Windows uses Cp1250 instead of UTF-8 as default encoding. I thought I configured build.gradle so that it uses correct encoding. But it seems I mistaken. I will fix the build script.

**Comment by asolntsev** [comment]
Hm... I tried to run Hangman tests on Windows, and it works. Can you specify version of OS, Java and Hangman you are using?

**Comment by tocumarian** [comment]
Hi and thanks for your time :)

I am using WIndows 8.1, Java JDK 1.8.0.31 x86, latest Hangman forked 4 days ago. Hmmm I am sure that I am doing something wrong :) so don't bother to much.

**Comment by asolntsev** [comment]
I have found the problem. In addition to this line in build.gradle:
```java
[compileJava, compileTestJava]*.options.collect {options -> options.encoding = 'UTF-8'}
```

I had to add this line:
```java
[compileScala, compileTestScala]*.options.collect {options -> options.encoding = 'UTF-8'}
```
